### ISSUE TITLE
http://ampersand.tarski.nl/RAP3 is not compiling.

### ISSUE THREAD

**Issue by dartheide** [AmpersandTarski/RAP#26] opened 2017-11-07 19:07 UTC
I' am following the instructions for the enrollment but the compile checkbox / save is not working.

Hans

**Comment by dartheide** [comment] 2017-11-08 20:52
[RAP issues26.pptx](https://github.com/AmpersandTarski/RAP/files/1455371/RAP.issues26.pptx)
Added powerpoint with screen dumps

**Comment by stefjoosten** [comment] 2017-11-09 16:30
Hi Hans, I can't reproduce this. Could you please call me on the phone?

**Comment by dartheide** [comment] 2017-11-09 17:09
Geen probleem op welk nummer?

Verstuurd vanaf mijn iPhone

**Comment by stefjoosten** [comment] 2017-11-11 06:44
# Symptoms
It seems that account 851833573 cannot recompile an existing script and account 123456 can...

**Comment by dartheide** [comment] 2017-11-11 10:25
An user created with SQL can compile but a user created by the RAP3 interface cannot compile.
The difference in table Account is the field accStudNr, that field is empty when the user is created by the RAP3 interface.  When I correct the field (with phpadmin) the user is able to compile. 

I used the following SQL statements;
INSERT INTO `Account`(`Account`,`accStudNr`,`accEmail`,`accNewPassword`,`accUserid`,`accPassword`,`accIsInitialized`,`accIsActive`,
	`accDeactivateReq`,`accPerson`,`ts_insertupdate`)
VALUES('Acc_Hans','851833574',NULL,NULL,'851833574','welkom','Acc_Hans','Acc_Hans',NULL,'Hans','2017-06-17 20:44:55');

INSERT INTO `UserID`(`UserID`,`Studentnummer`,`ts_insertupdate`)
VALUES('851833574','851833574','2017-06-17 20:44:53'); 

INSERT INTO `Actor`(`Actor`,`Person`,`personMiddle`,`personFirstName`,`personLastName`,`ts_insertupdate`)
VALUES('Hans','Hans','','Hans','Voorwinden','2017-06-17 20:44:52');

INSERT INTO `accAllowedRoles` (`Account`, `Role`, `ts_insertupdate`) 
VALUES('Acc_Hans', 'Student', '2017-06-17 20:44:52');

INSERT INTO `accAllowedRoles` (`Account`, `Role`, `ts_insertupdate`) 
VALUES('Acc_Hans', 'User', '2017-06-17 20:44:55');

INSERT INTO `accDefaultRoles` (`Account`, `Role`, `ts_insertupdate`) 
VALUES('Acc_Hans', 'User', '2017-06-17 20:44:55');

**Comment by stefjoosten** [comment] 2020-12-14 18:50
fixed on https://rap.cs.ou.nl.

**Closed** 2020-12-14 18:50 UTC
