### ISSUE TITLE
Missing stuff (in concepts.json and other files)

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/RAP#11] opened 2016-11-22 08:51 UTC
I use `Ampersand-v3.7.2 [development:21e1172]`
I have installed the RAP3 stuff on my local machine.
I have NOT installed latex.

The picture below shows:

1. that I have a script (not uploaded, just copied into the editor) that is correct
2. that an analysis does not provide a link to the meatgrinder stuff.

![image](https://cloud.githubusercontent.com/assets/8522589/20516691/00e27dfa-b098-11e6-8fcc-b3e8ab9254a6.png)

**ANALYSYS**
First, we get an error indicating that the concept `DatabaseName` is missing, which causes line 228 in `cli.php` to produce an error. 
After adding `dbName :: Context * DatabaseName [UNI]` in the RAP3.adl script, this error is gone, but we then still get an error - now about `SQLPlug` - as shown in the figure below.

![image](https://cloud.githubusercontent.com/assets/8522589/20516884/f4602522-b098-11e6-95fd-458c0f74c24f.png)

**DIAGNOSIS**
The `concepts.json` file (and others perhaps) do not contain sufficient meatgrinder information to run the  function `loadPopInRAP3` correctly.

**Comment by hanjoosten** [comment] 2016-11-22 18:40
I cannot reproduce this error. Very strange. I also checked for any forgotten-to-add-to-the-repo-files, but that isn't the case. 
@stefjoosten and/or @Michiel-s : Can you reproduce this?
@RieksJ : Is ampersand.exe in your path, or could this be caused because you do local scripting?
I am clueless about what is going on here.

**Comment by stefjoosten** [comment] 2016-11-22 19:27
@RieksJ does the problem go away after installing the LaTeX stuff?

**Comment by hanjoosten** [comment] 2016-11-22 20:20
@stefjoosten : Do you get this same error, when you build RAP3?

**Comment by RieksJ** [comment] 2016-11-23 06:06
I'm not going through all the hassle of installing LaTeX again. Like @stefjoosten I cannot imagine that it is to blame. @Michiel-s and I have seen that information that prototypes need is missing from the `concepts.json` file (and maybe others, too). So that's where we should look first.

**Comment by RieksJ** [comment] 2016-11-23 07:02
Upon @hanjoosten's request, I have compiled the last version that he has checked in (RAP dfc20db) using the latest ampersand development version (6b61595). I have also compiled this version using an earlier Ampersand version (21e1172) and a still older one (86835a7). I use the command line
~~~
"C:\Ampersand\AMPprogs\ampersand.exe" "RAP3.adl" --meta-tables --proto -p"C:\xampp\htdocs\GENDIR"
~~~
to compile in the (nonexistent) directory `GENDIR`, which is subsequently renamed into `RAP3` for running the stuff. Nothing special here. 

The result is consistently produce the same error, as shown in the two figures here below. Note that the error here is the error I originally mentioned,  namely that the concept `DatabaseName` is lacking from `Concepts.json`:
![image](https://cloud.githubusercontent.com/assets/8522589/20553210/ea086656-b152-11e6-8c6f-cb8d34bb8038.png)
![image](https://cloud.githubusercontent.com/assets/8522589/20553193/cdf01ec8-b152-11e6-8640-38638ce6755b.png)

**Comment by RieksJ** [comment] 2016-11-24 12:02
Just for the record: @Michiel-s en ik hebben vastgesteld dat dit probleem zich niet voordoet op Michiel's machine. Wel op die van Rieks, en is _onafhankelijk_ van

- het al dan niet gebruiken van scripts (Rieks doet dat wel, maar ook als hij dat alleen op de commandline doet zien we het probleem)
- welke versie van Ampersand is gebruikt (getest met de laatste 3 van het moment, en ook met een aantal versies van een paar weken geleden)

In een gesprek met @hanjoosten is gebleken dat enige maanden geleden een wijziging is aangebracht die hier mee te maken zou kunnen hebben - Han gaat dat nakijken.

**Comment by RieksJ** [comment] 2016-11-28 19:57
Spending an evening with Han pointed us to the error: it turns out that the assumption that is being made in `cli.php`, namely that `ampersand` (i.e. the executable) is in the PATH, is not something that you can rely on, even if you explicitly instruct guys like me to set the path accordingly, and checking (e.g. with Michiel and Han earlier) that the path is properly set. That this actually is the problem is shown when I modify every occurrance of `ampersand` with the explicit path that I use (i.e. `C:\Ampersand\AMPprogs\ampersand.exe`).

To solve this issue I propose to define a configuration variable, to be specified in `localsettings.php`, that specifies the executable and its path.

To prevent issues like these to occur in the future, I propose that we (gradually?) revise the code of `cli.php` to do thorough testing of all input- and configuration parameters that are being used.

**Comment by RieksJ** [comment] 2016-11-28 20:49
I have checked in a new version of RAP3, that fixes the problem under the assumption that the path to the ampersand executable be configured in `localSettings.php`. This may not be the ultimate/final solution, but at least anyone can get it to work now.

**Comment by RieksJ** [comment] 2016-11-29 07:07
I remembered that this ticket originally was about "Missing stuff (in concepts.json...", saying that the concept `DatabaseName` was not to be found in `concepts.json`. While the error that triggered this issue has gone, I still cannot find `DatabaseName` in `concepts.json`. @Michiel-s: care to comment on why this is not necessary while we originally thought it was?

**Comment by hanjoosten** [comment] 2016-11-30 07:01
@Rieks, In retrospect, looking at the earlier reports you did about this issue, I see a comment of seven days ago (the one with the second screendump in this thread). 
At that time, you were able to call ampersand.exe successfully:
![image](https://cloud.githubusercontent.com/assets/1159672/20742598/579b953e-b6d1-11e6-905a-d33199332bf7.png)
Note the result of ampersand.exe, saying: 'Finished processing your model', which is proof of my claim. 

Did you change any php settings (e.g., enable 'safe mode'?)

**Comment by RieksJ** [comment] 2016-11-30 07:36
No. I die nog do any such thing.

Verzonden met mijn Windows Phone
________________________________

**Comment by hanjoosten** [comment] 2016-11-30 07:42
Well, PHP could find ampersand.exe on your machine last week. How come?

**Comment by RieksJ** [comment] 2016-11-30 08:12
Beats me. I conclude that I want to be robust against (I.e. Independent of)  such uncertainties.

Verzonden met
________________________________

**Comment by hanjoosten** [comment] 2016-12-01 21:58
I think we should close this issue, for there is nothing more to it. If anyone likes to reopen it, please do so with a motivation.

**Closed by hanjoosten** 2016-12-01 21:58 UTC
Labels: in progress, question
