### ISSUE TITLE
New password page has dozens of fields for repeated passwords

### ISSUE THREAD

**Issue by LloydRutledge** [AmpersandTarski/RAP#119] opened 2021-01-30 13:03 UTC
I made a new account and got forwarded to the page for entering a new password. It began as expected: with a row with two fields: one for the new password, and the second for repeating entry of the new password to check that it's the same because entry is hidden. The problem is that row appears dozen of times, instead of just once.

![top](https://user-images.githubusercontent.com/1098321/106357002-c8368500-6303-11eb-9ddb-a72fccf677bf.jpg)

![bottom](https://user-images.githubusercontent.com/1098321/106357007-cb317580-6303-11eb-95c8-037f5d5e7d3a.jpg)

**Comment by hanjoosten** [comment] 2021-01-30 13:19
This issue is a duplicate of https://github.com/AmpersandTarski/RAP/issues/113

**Comment by RieksJ** [comment] 2021-02-08 09:00
I'm surprised the [proposed fix](https://github.com/AmpersandTarski/RAP/issues/113#issuecomment-753797158) has not yet been implemented in RAP.

**Comment by stefjoosten** [comment] 2021-02-09 20:26
Fixed! See comments in issue #113 for the solution. I have implemented the solution on rap.cs.ou.nl just now.

**Closed** 2021-02-09 20:27 UTC
