### ISSUE TITLE
404 page not found with Enrollment tutorial example prototype generation

### ISSUE THREAD

**Issue by LloydRutledge** [AmpersandTarski/RAP#92] opened 2020-11-27 15:54 UTC
Four different groups of OU-RBD students have been getting "404 page not found" and/or "Bad gateway" and similar messages when putting the tutorial's enrollment code on the course's RAP4 server and generating prototypes from it. They take the code from https://ampersandtarski.gitbook.io/documentation/tutorial-rap3/example-system-enrollment and put in in the server editor and compile it and generate services from it including the prototype

Here is a screendump one student generated for getting up to the generation of the prototype link: 

<img width="1151" alt="AmpEdit" src="https://user-images.githubusercontent.com/1098321/100465847-48f0bf00-30d0-11eb-8023-3e9ba19a7cbe.png">

And then clicking on the prototype link gives him this:

<img width="798" alt="BadGate" src="https://user-images.githubusercontent.com/1098321/100466094-a71da200-30d0-11eb-8c6d-c06b95839b47.png">

Other students get a 404 error from that link.

Stef, can you fix this on the course server? Each upcoming week to the beginning of February give the 70 students a specific portion of the tutorial to study. This week was the tutorial, and thus the multiple reports. It would be nice if these students can easily apply Ampersand to writing their advise reports in these same weeks.

**Comment by hanjoosten** [comment] 2020-11-27 16:50
@stefjoosten , I could reproduce this behaviour on my own docker platform. Not sure exactly what is going on. This probably is network related stuff. 

In the logs, I had several instances looking like this:

~~~
rap4                       | [2020-11-27 16:20:18] EXECENGINE.INFO: CompileWithAmpersand(prototype,Script_1606493936_00633443,ScriptVersion_1606493955_00159922,scripts/hopseflops/Script_1606493936_00633443/ScriptVersion_1606493955_00159922/script.adl,hopseflops) [] {"request_id":"aa36d77553","ip":"172.18.0.2
","method":"PATCH","url":"/api/v1/resource/Script/Script_1606493936_00633443/Nieuw_32_script"}
rap4                       | [2020-11-27 16:20:18] EXECENGINE.INFO: Executing cmd: 'docker rm -f "hopseflops" 2>&1' (cwd: '/var/www/public/api/v1') [] {"request_id":"aa36d77553","ip":"172.18.0.2","method":"PATCH","url":"/api/v1/resource/Script/Script_1606493936_00633443/Nieuw_32_script"}
rap4                       | [2020-11-27 16:20:18] EXECENGINE.INFO: Executing cmd: 'echo "Q09OVEVYVCBFbnJvbGxtZW50IElOIERVVENIClBVUlBPU0UgQ09OVEVYVCBFbnJvbGxtZW50CnsrIEEgY29tcGxldGUgY291cnNlIGNvbnNpc3RzIG9mIHNldmVyYWwgbW9kdWxlcy4KU3R1ZGVudHMgb2YgYSBjb3Vyc2UgY2FuIGVucm9sbCBmb3IgYW55IG1vZHVsZSB0aGF0IGlzIHBhcnQ
gb2YgdGhlIGNvdXJzZS4KK30KClBBVFRFUk4gQ291cnNlcwotLSBUaGUgY29uY2VwdHMKQ09OQ0VQVCBTdHVkZW50ICJTb21lb25lIHdobyB3YW50cyB0byBzdHVkeSBhdCB0aGlzIGluc3RpdHV0ZSIKQ09OQ0VQVCBDb3Vyc2UgIkEgY29tcGxldGUgY291cnNlIHRoYXQgcHJlcGFyZXMgZm9yIGEgZGlwbG9tYSIKQ09OQ0VQVCBNb2R1bGUgIkFuIGVkdWNhdGlvbmFsIGVudGl0eSB3aXRoIGEgc2luZ2xlIGV4YW0iCgo
tLSBUaGUgcmVsYXRpb25zIGFuZCB0aGUgaW5pdGlhbCBwb3B1bGF0aW9uClJFTEFUSU9OIHRha2VzIFtTdHVkZW50KkNvdXJzZV0gW1RPVF0KTUVBTklORyAiQSBzdHVkZW50IHRha2VzIGEgY29tcGxldGUgY291cnNlIgoKUE9QVUxBVElPTiB0YWtlcyBDT05UQUlOUwogICBbICgiUGV0ZXIiLCAiTWFuYWdlbWVudCIpCiAgIDsgKCJTdXNhbiIsICJCdXNpbmVzcyBJVCIpCiAgIDsgKCJKb2huIiwgIkJ1c2luZXNzIEl
UIikKICAgXQoKUkVMQVRJT04gaXNQYXJ0T2YgW01vZHVsZSpDb3Vyc2VdCk1FQU5JTkcgIkEgbW9kdWxlIHBhcnQgb2YgYSBjb21wbGV0ZSBjb3Vyc2UiCgpQT1BVTEFUSU9OIGlzUGFydE9mIENPTlRBSU5TCiAgIFsgKCJGaW5hbmNlIiwgIk1hbmFnZW1lbnQiKQogICA7ICgiQnVzaW5lc3MgUnVsZXMiLCAiQnVzaW5lc3MgSVQiKQogICA7ICgiQnVzaW5lc3MgQW5hbHl0aWNzIiwgIkJ1c2luZXNzIElUIikKICAgOyA
oIklULUdvdmVybmFuY2UiLCAiQnVzaW5lc3MgSVQiKQogICA7ICgiSVQtR292ZXJuYW5jZSIsICJNYW5hZ2VtZW50IikKICAgXQoKUkVMQVRJT04gaXNFbnJvbGxlZEZvciBbU3R1ZGVudCpNb2R1bGVdCk1FQU5JTkcgIlN0dWRlbnRzIGVucm9sbCBmb3IgZWFjaCBtb2R1bGUgaW4gdGhlIGNvdXJzZSBzZXBhcmF0ZWx5IgoKLS0gVGhlIG9uZSBydWxlIGluIHRoaXMgbW9kZWwKUlVMRSBNb2R1bGVFbnJvbGxtZW50OiB
pc0Vucm9sbGVkRm9yIHwtIHRha2VzO2lzUGFydE9mfgpNRUFOSU5HICJBIHN0dWRlbnQgY2FuIGVucm9sbCBmb3IgYW55IG1vZHVsZSB0aGF0IGlzIHBhcnQgb2YgdGhlIGNvdXJzZSB0aGUgc3R1ZGVudCB0YWtlcyIKTUVTU0FHRSAiQXR0ZW1wdCB0byBlbnJvbGwgc3R1ZGVudChzKSBmb3IgYSBtb2R1bGUgdGhhdCBpcyBub3QgcGFydCBvZiB0aGUgc3R1ZGVudCdzIGNvdXJzZS4iClZJT0xBVElPTiAoVFhUICJTdHV
kZW50ICIsIFNSQyBJLCBUWFQgIiBlbnJvbGxlZCBmb3IgdGhlIG1vZHVsZSAiLCBUR1QgSSwgVFhUICIgd2hpY2ggaXMgbm90IHBhcnQgb2YgdGhlIGNvdXJzZSAiLCBTUkMgSVtTdHVkZW50XTt0YWtlcykKRU5EUEFUVEVSTgoKSU5URVJGQUNFIE92ZXJ2aWV3IDogIl9TRVNTSU9OIiAgICAgICAgICAgICAgICAgY1J1ZApUQUJTIFsgU3R1ZGVudHMgICAgIDogVltTRVNTSU9OKlN0dWRlbnRdICAgICAgICBjUnVECiA
gICAgICBDT0xTIFsgIlN0dWRlbnQiIDogSVtTdHVkZW50XSAgICAgICAgICAgIGNSdUQgCiAgICAgICAgICAgICwgIkVucm9sbGVkIGZvciIgOiBpc0Vucm9sbGVkRm9yICAgIGNSVUQKICAgICAgICAgICAgLCAiQ291cnNlIiA6IHRha2VzICAgICAgICAgICAgICAgICAgQ1JVRCAKICAgICAgICAgICAgXQogICAgICwgQ291cnNlICAgICA6IFZbU0VTU0lPTipDb3Vyc2VdICAgICAgICAgICBjUnVECiAgICAgICBDT0x
TIFsgIkNvdXJzZSIgOiBJICAgICAgICAgICAgICAgICAgICAgIGNSdWQKICAgICAgICAgICAgLCAiTW9kdWxlcyIgOiBpc1BhcnRPZn4gICAgICAgICAgICAgQ1JVRAogICAgICAgICAgICBdCiAgICAgLCBNb2R1bGVzIDogVltTRVNTSU9OKk1vZHVsZV0gICAgICAgICAgICAgIGNSdWQKICAgICAgIENPTFMgWyAiTW9kdWxlcyIgOiBJICAgICAgICAgICAgICAgICAgICAgY1J1RAogICAgICAgICAgICAsICJDb3Vyc2U
iIDogaXNQYXJ0T2YgICAgICAgICAgICAgICBjUnVkCiAgICAgICAgICAgICwgIlN0dWRlbnRzIiA6IGlzRW5yb2xsZWRGb3J+ICAgICAgIENSVUQKICAgICAgICAgICAgXQogICAgIF0KCkVORENPTlRFWFQ=" | docker run --name "hopseflops" --rm -i -a stdin --network proxy --label traefik.enable=true --label traefik.http.routers.hopseflops-insecure.rule="Host(\`h
opseflops.localhost\`)" --label student-prototype -e AMPERSAND_DBHOST=db -e AMPERSAND_DBNAME="student_hopseflops" -e AMPERSAND_DBUSER=ampersand -e AMPERSAND_DBPASS=somepasswordhere -e AMPERSAND_PRODUCTION_MODE="false" -e AMPERSAND_DEBUG_MODE="true" -e AMPERSAND_SERVER_URL="https://hopseflops.localhost" -e AMPERSAND
_LOG_CONFIG=logging.yaml ampersandtarski/rap4-student-prototype:v1.0.0 2>&1' (cwd: '/var/www/public/api/v1') [] {"request_id":"aa36d77553","ip":"172.18.0.2","method":"PATCH","url":"/api/v1/resource/Script/Script_1606493936_00633443/Nieuw_32_script"}
rap4                       | [Fri Nov 27 16:20:18.558608 2020] [php7:warn] [pid 20] [client 172.18.0.2:41724] PHP Warning:  implode(): Invalid arguments passed in /var/www/extensions/RAP4/src/Command.php on line 56, referer: http://localhost/
rap4                       | [2020-11-27 16:20:18] EXECENGINE.INFO: Executing cmd: 'docker network connect rap_db hopseflops  2>&1' (cwd: '/var/www/public/api/v1') [] {"request_id":"aa36d77553","ip":"172.18.0.2","method":"PATCH","url":"/api/v1/resource/Script/Script_1606493936_00633443/Nieuw_32_script"}
rap4                       | [2020-11-27 16:20:18] CORE.INFO: Link added to relation: (ScriptVersion_1606493955_00159922[ScriptVersion],ScriptVersion_1606493955_00159922[ScriptVersion]) protoOk[ScriptVersion*ScriptVersion] [] {"request_id":"aa36d77553","ip":"172.18.0.2","method":"PATCH","url":"/api/v1/resour
ce/Script/Script_1606493936_00633443/Nieuw_32_script"}
rap4                       | [2020-11-27 16:20:18] CORE.INFO: Link deleted: (ScriptVersion_1606493955_00159922[ScriptVersion],ScriptVersion_1606493955_00159922[ScriptVersion]) protoOk[ScriptVersion*ScriptVersion] [] {"request_id":"aa36d77553","ip":"172.18.0.2","method":"PATCH","url":"/api/v1/resource/Script/
Script_1606493936_00633443/Nieuw_32_script"}
~~~
Especially notice the line that says 
~~~
PHP Warning:  implode(): Invalid arguments passed in /var/www/extensions/RAP4/src/Command.php on line 56, referer: http://localhost/
~~~

**Comment by hanjoosten** [comment] 2020-11-27 17:10
I think we need to ask @Michiel-s to have a look. I have a feeling that this could be caused by the fix of https://github.com/AmpersandTarski/RAP/issues/85 . In that solution the container of the student was trashed, just before building a fresh one. Could it be the case that the container was succesfully trashed, but not built successfully? In that case I can imagine a `bad gateway` error.

**Comment by stefjoosten** [comment] 2020-11-27 22:07
The prototype runs on http. All other pages in RAP4 run on https. Could it be that certain browsers give a 404 on http pages? Could that cause this behaviour? @Michiel-s do you have a clue?

**Comment by stefjoosten** [comment] 2020-11-28 06:53
Sorry, I closed this issue prematurely. It is the same as issue#90, by the way.

**Comment by stefjoosten** [comment] 2020-11-28 07:06
# Analysis
 I can reproduce this on Firefox, but not on Chrome. With Chrome it works fine (on my laptop). It seems that this issue appears on Firefox browsers.

Hypothesis: this has to do with Firefox refusing HTTP. 
@LloydRutledge please ask your students to try if the problem still occurs on Chrome.

**Comment by stefjoosten** [comment] 2020-11-28 07:58
# Fix
I found a fix, but I don't know why it fixes the problem. I have set the environment variable `AMPERSAND_DEBUG_MODE=false`. This works. @LloydRutledge can you verify that the problem is solved?

@Michiel-s Do we have an explanation? Otherwise, I cannot be sure this problem is fixed.

**Comment by LloydRutledge** [comment] 2020-11-28 08:00
I'll suggest that the students try Chrome now, and try it myself later today. Thanks for looking into it so quickly!
________________________________

**Comment by Michiel-s** [comment] 2020-11-28 08:06
I'm looking into it. Not sure yet, but the hint of @hanjoosten about the warning for implode function might be of importance.

**Comment by LloydRutledge** [comment] 2020-11-28 08:13
Actually, I've been using Chrome the whole time and getting this problem, so I don't think that's the problem. Perhaps it has to do with settings on either, and more, browers?

Now I've recompiled the same, save Enrollment script on the server and have a new bug, so I can't check this bug. I'll post the new bug separately.

**Comment by Michiel-s** [comment] 2020-11-28 08:17
> I'm looking into it. Not sure yet, but the hint of @hanjoosten about the warning for implode function might be of importance.

Ok. The warning here is NOT the problem. You can ignore that one.

**Comment by Michiel-s** [comment] 2020-11-28 08:45
After some searching I'm pretty sure it is a docker network issue for traefik proxy. We need to add an extra label for the student prototype generation. In `ExecEngineFunctions.php` around line 260, add `--label traefik.docker.network=proxy`
I think that should do the trick, and/or is at least an improvement for stability.

**Comment by LloydRutledge** [comment] 2020-11-28 08:46
I've gotten around the new bug (#91) by refreshing, recompiling and not generating an atlas. So now I can generate and click the prototype. However, now, again, and on Chrome, I still get a bad gateway.

**Comment by Michiel-s** [comment] 2020-11-28 08:51
> I've gotten around the new bug (#91) by refreshing, recompiling and not generating an atlas. So now I can generate and click the prototype. However, now, again, and on Chrome, I still get a bad gateway.

Hi @LloydRutledge, see my comment above. I don't think it has anything to do with the browser you are using. It is an issue with the proxy service (traefik) not being able to reach the backend service. I think implementing the change I suggest will do the trick. @stefjoosten can do that and rollout a new version of RAP4

**Comment by LloydRutledge** [comment] 2020-11-28 08:52
My normal browser is Chrome. I just tried Edge and Firefox and both give the same bad gateway when clicking the prototype link. Each time I got to the saved script, recompile, generate prototype, then click on prototype. With Firefox I imported my data from Chrome (perhaps including cookies?) and with Edge I didn't.

**Comment by Michiel-s** [comment] 2020-11-28 09:08
> My normal browser is Chrome. I just tried Edge and Firefox and both give the same bad gateway when clicking the prototype link. Each time I got to the saved script, recompile, generate prototype, then click on prototype. With Firefox I imported my data from Chrome (perhaps including cookies?) and with Edge I didn't.

I don't think it has to do with the kind of browser.. see my comment above.

**Comment by stefjoosten** [comment] 2020-11-29 07:51
@Michiel-s wrote:
> After some searching I'm pretty sure it is a docker network issue for traefik proxy. We need to add an extra label for the student prototype generation. In `ExecEngineFunctions.php` around line 260, add `--label traefik.docker.network=proxy`
> I think that should do the trick, and/or is at least an improvement for stability.

I did this and it seems to improve things. However, it still gives an unsafe service:
<img width="432" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/100536274-d3940400-321f-11eb-9140-d889e919658c.png">

**Comment by Michiel-s** [comment] 2020-11-29 07:53
Yes unsafe, as in http without TLS, because we haven't implemented that part for student prototypes.

**Comment by stefjoosten** [comment] 2020-11-29 07:56
@Michiel-s can you explain how the environment variable `AMPERSAND_DEBUG_MODE` relates to this? (see "Fix" in a previous comment)

**Comment by stefjoosten** [comment] 2020-11-29 08:00
The `bad gateway` thing still persists. I think this is because Traefik needs some time to react to the new service.

**Comment by Michiel-s** [comment] 2020-11-29 08:03
> @Michiel-s can you explain how the environment variable `AMPERSAND_DEBUG_MODE` relates to this? (see "Fix" in a previous comment)

It doesn't relate to this issue. This 'Bad gateway' issue is about traefik proxy not being always able to find the backend service in the right docker network. When having multiple docker networks (as we do: proxy, db, ..) and not specifying explicitly in which network the proxy needs to look, you get this unexpected behavior. This is what @stefjoosten told me after he contacted the support desk from Traefik.

What I think happened is that you changed the environment variable, after which the RAP container is restarted and changes are made in the docker network which triggered traefik to scan the network again or something like that.

**Comment by stefjoosten** [comment] 2020-11-29 08:05
The 404 issue has also not vanished...
<img width="449" alt="Schermafbeelding 2020-11-29 om 09 02 51" src="https://user-images.githubusercontent.com/275768/100536585-f0c9d200-3221-11eb-908e-c437c21d81fd.png">

**Comment by Michiel-s** [comment] 2020-11-29 08:05
> The `bad gateway` thing still persists. I think this is because Traefik needs some time to react to the new service.

I just created a prototype of my own on the OU server and it went perfectly fine: http://michiel.rap.cs.ou.nl/

**Comment by Michiel-s** [comment] 2020-11-29 08:08
> The 404 issue has also not vanished...
> <img alt="Schermafbeelding 2020-11-29 om 09 02 51" width="449" src="https://user-images.githubusercontent.com/275768/100536585-f0c9d200-3221-11eb-908e-c437c21d81fd.png">

That is because the prototype is down I guess. It's the same message as when you try something random like http://something.rap.cs.ou.nl

**Comment by stefjoosten** [comment] 2020-12-14 14:18
fixed

**Closed by stefjoosten** 2020-12-14 14:18 UTC
Labels: RAP4
