### ISSUE TITLE
RAP3 save script after changes doesn't seem to be happening

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/RAP#30] opened 2017-11-21 09:04 UTC
This is probably related to #28 
I change some code, click on "beware to save..." and the counter on the error message "DelAtom() expects 2 arguments, but you provided 10" increases and no changes have been saved.

**Comment by stefjoosten** [comment] 2017-11-21 18:52
@EstherHageraats, would you test and close this issue, please? (Or leave it open if the issue is still there...)

**Comment by EstherHageraats** [comment] 2017-11-22 07:39
This issue is still there.

**Comment by stefjoosten** [comment] 2017-11-22 16:08
You are quite right. I have not fixed this bug completely. (Shame on me)

**Comment by hanjoosten** [comment] 2017-11-22 21:03
I am afraid that the syntax change has an unforseen effect on the string that we provide to the execengine. In the past, an atom was allways represented as a string (with quotes). Now the quotes are not present anymore. It is likely that this is the cause of this problem. 

This Will likely need more time to investigate and solve 🙁

**Comment by stefjoosten** [comment] 2017-11-22 22:50
I have disabled the erroneous rule. @EstherHageraats, would you please retry ?

The problem has not been solved, but I hope RAP3 does not touch this bug anymore.
We still need to make a good diagnosis and solve the problem.
I'm leaving this issue open, even though Esther might be able to work now.

# Analysis
It appears we have a `BIGALPHANUMERIC` string in a concept table, which needs to be deleted. When `DelAtom` gets this string, it has not been escaped so every double quote in it affects the PHP syntax. This is a code insertion error.
I have questions about it:
* Why did we put a `BIGALPHANUMERIC` string in a concept table in the first place? That seems unnecessary...
* Without doubt, there is an escaping function in PHP. But where do we call it to fix the code insertion problem?

**Comment by hanjoosten** [comment] 2017-11-23 05:03
### Answer to question 1.

At a meta-level, there are several concepts that must be `BIGALPHANUMERIC`. Think about `ShowAdl` or `Purpose`. The atoms of these concepts are represented by a string, and it is obvious that in theory there is no upperbound to the lenght of these strings. In practice, since they must be stored into the database, we must choose a representation type that is stringlike, such as `ALPHANUMERIC`, `BIGALPHANUMERIC` or even `HUGEALPHANUMERIC`. The first one limits the string to a lenght of at best 255 characters. This is too short. Therefor, we need `BIGALPHANUMERIC`.

### Comments to question 2:
This is probably [mysqli_escape_string](http://php.net/manual/en/function.mysqli-escape-string.php). Further investigation is required to where to put this exactly. It might be in the adl script :worried:

**Closed** 2017-11-24 05:31 UTC
Labels: bug, RAP3

**Comment by stefjoosten** [comment] 2017-11-24 05:46
This is a bug in Ampersand rather than in RAP3. I am closing this issue here. It is continued in issue AmpersandTarski/Ampersand/issues/717.
